services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: WheaterApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: ChartWheaterApi/Dockerfile
    environment:
      - API_BASE_URL=http://localhost/api/  # nginx vai encaminhar para o backend
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
